version: '3.8'
services:
  db:
    build: . #Dockerfileが置いてあるディレクトリへの相対パスを記述
    container_name: docker-mysql-hands-on
    platform: linux/x86_64
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: movie_information
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - 3307:3306
    volumes:
      - ./sql:/docker-entrypoint-initdb.d #　ホストディレクトリ : コンテナ内ディレクトリ （またSQLの初期データ）
      - my-vol:/var/lib/mysql #　ホストディレクトリ : コンテナ内ディレクトリ
volumes:
  my-vol:
